#!/bin/sh

set -e

if [ -t 1 ] ; then
  # Yes, a TTY
  true
else
  echo "Not a TTY, exiting"

  exit 0
fi

bin/lint

bin/rails css:build
bin/rails javascript:build

export HEADLESS=1
export COVERAGE=1
export RUBYOPT="--enable=frozen-string-literal --debug=frozen-string-literal"

bin/rails test:all
