version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
    groups:
      herb:
        patterns:
          - "@herb-tools/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
