version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    cooldown:
      semver-major-days: 21
      semver-minor-days: 14
      semver-patch-days: 7
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      semver-major-days: 21
      semver-minor-days: 14
      semver-patch-days: 7
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
    groups:
      herb:
        patterns:
          - "@herb-tools/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:30"
      timezone: "America/New_York"
      day: "saturday"
    cooldown:
      default-days: 21
