---
EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  PartialInstanceVariable:
    enabled: true
  SpaceInHtmlTag:
    enabled: false
  StrictLocals:
    enabled: true
  TrailingWhitespace:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
