files:
  exclude:
    - "coverage/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

linter:
  enabled: true

  rules:
    # FIXME: enable
    erb-no-duplicate-branch-elements:
      enabled: false

    # FIXME: enable
    erb-no-interpolated-class-names:
      enabled: false

    # FIXME: enable
    erb-no-unsafe-raw:
      enabled: false

    # FIXME: enable
    html-img-require-alt:
      enabled: false

formatter:
  enabled: true
