default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oiva_development

test:
  <<: *default
  database: oiva_test
  host: localhost
  username: <%= ENV['OIVA_DATABASE_USERNAME'] %>
  password: <%= ENV['OIVA_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: oiva_production
  username: oiva
  password: <%= ENV['OIVA_DATABASE_PASSWORD'] %>
