#!/bin/sh

set -e

PATH="node_modules/.bin:$PATH"

# run-pty is a modern foreman alternative for local development
# See https://github.com/lydell/run-pty for docs
# See ./run-pty.json for our configuration

RUBYOPT="--enable=frozen-string-literal --debug=frozen-string-literal" run-pty run-pty.json
