name: Mergeabot

on:
  schedule:
    - cron: "0 16 * * 1-5"

  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  mergeabot:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/mergeabot-action@v1
        with:
          strategy: squash
